name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Build the project
        run: mvn clean package -DskipTests

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:login
          heroku create $HEROKU_APP_NAME --region=us
          heroku container:push web --app $HEROKU_APP_NAME
          heroku container:release web --app $HEROKU_APP_NAME
