name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (Full Clone Fix)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ This prevents shallow clones

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Build the project
        run: mvn clean package -DskipTests

      # ✅ FIX: Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # ✅ FIX: Convert shallow clone to full clone
      - name: Convert shallow clone to full clone
        run: git fetch --unshallow

      - name: Deploy to Heroku using Git
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku auth:token
          heroku git:remote -a $HEROKU_APP_NAME
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/main -f
